In [2]:
import numpy as np

In [6]:
a1 = np.array([1,2,3,4,5])

In [7]:
a1

array([1, 2, 3, 4, 5])

In [8]:
type(a1)

numpy.ndarray

In [10]:
Zeros = np.zeros((1,2))
Zeros

array([[0., 0.]])

In [15]:
Random = np.random.random(4)

In [16]:
Random

array([0.67923056, 0.45731565, 0.74972173, 0.4533219 ])